services:
  app:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    volumes:
      - ./data/webui:/app/backend/data
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - WEBUI_SESSION_COOKIE_SECURE=${WEBUI_SESSION_COOKIE_SECURE}
      - WEBUI_AUTH_COOKIE_SAME_SITE=${WEBUI_AUTH_COOKIE_SAME_SITE}
      - WEBUI_AUTH_COOKIE_SECURE=${WEBUI_AUTH_COOKIE_SECURE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'com.centurylinklabs.watchtower.scope=open-webui'

  auto-update:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      # - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_LOG_FORMAT=json
      - WATCHTOWER_POLL_INTERVAL=1800
      # - WATCHTOWER_DEBUG=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      # Monitor and update containers that have a `com.centurylinklabs.watchtower.enable` label set to `true`
      - WATCHTOWER_LABEL_ENABLE=true
      # Update containers that have a `com.centurylinklabs.watchtower.scope` label set with the same value as the given argument. This enables running multiple instances.
      - WATCHTOWER_SCOPE=open-webui
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
      - 'com.centurylinklabs.watchtower.scope=open-webui'
