services:
  web:
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      - 'traefik.http.services.karakeep.loadbalancer.server.port=3000'
      # HTTPS Host
      - 'traefik.http.routers.karakeep.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.karakeep.entrypoints=websecure'
      - 'traefik.http.routers.karakeep.tls=true'
      - 'traefik.http.routers.karakeep.tls.certResolver=webcert'
      - 'traefik.http.routers.karakeep.service=karakeep'

  chrome:
    networks:
      - default

  meilisearch:
    networks:
      - default

networks:
  traefik:
    external: true
