services:
  web:
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      - 'traefik.http.services.hoarder.loadbalancer.server.port=3000'
      # HTTPS Host
      - 'traefik.http.routers.hoarder.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.hoarder.entrypoints=websecure'
      - 'traefik.http.routers.hoarder.tls=true'
      - 'traefik.http.routers.hoarder.tls.certResolver=webcert'
      - 'traefik.http.routers.hoarder.service=hoarder'

  chrome:
    networks:
      - default

  meilisearch:
    networks:
      - default

networks:
  traefik:
    external: true
