version: '3.8'

# -v <host docker sock>:/var/run/docker.sock

services:
  app:
    image: 1dev/server
    restart: unless-stopped
    volumes:
      - ./data/onedev:/opt/onedev
    environment:
      INITIAL_USER: ${INITIAL_PASSWORD}
      INITIAL_PASSWORD: ${INITIAL_PASSWORD}
      INITIAL_EMAIL: ${INITIAL_EMAIL}
      INITIAL_SERVER_URL: ${INITIAL_SERVER_URL}
      # SSH root url of this server (will derive from initial_server_url if left empty)
      # INITIAL_SSH_ROOT_URL: ${INITIAL_SSH_ROOT_URL}

      # TODO: Update setup to use Postgres instead of internal DB
      # db:
      #   image: postgres:15-alpine
      #   restart: unless-stopped
      #   environment:
      #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #     POSTGRES_USER: ${POSTGRES_USER}
      #     POSTGRES_DB: ${POSTGRES_DATABASE}
      #   healthcheck:
      #     test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      #     interval: 10s
      #     timeout: 2s
      #     retries: 10
