services:
  wyze-bridge:
    image: mrlt8/wyze-bridge:latest
    restart: unless-stopped
    ports:
      - ${PORT_RTMP}:1935 # RTMP
      - ${PORT_RTSP}:8554 # RTSP
      - ${PORT_HLS}:8888 # HLS
      - ${PORT_WEBRTC}:8889 # WebRTC
      - ${PORT_WEBRTC_ICE}:8189/udp # WebRTC/ICE
      - ${PORT_WEBUI}:5000 # Web-UI
    environment:
      - API_ID=${API_ID}
      - API_KEY=${API_KEY}
      - WYZE_EMAIL=${WYZE_EMAIL}
      - WYZE_PASSWORD=${WYZE_PASSWORD}
      - WB_IP=${WB_IP}
      - WB_AUTH=${WB_AUTH}
      - WB_USERNAME=${WB_USERNAME}
      - WB_PASSWORD=${WB_PASSWORD}
