services:
  timescale:
    # Includes the TimescaleDB Toolkit, and support for PostGIS and Patroni
    image: timescale/timescaledb-ha:pg17
    # Smaller image
    # image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    volumes:
      - ./data/timescale:/home/postgres/pgdata/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
