version: '3.8'

services:
  heimdall:
    networks:
      - traefik
    # ports:
    #   - 80:80
    #   - 443:443
    labels:
      - 'traefik.enable=true'
      # HTTPS Host
      - 'traefik.http.routers.heimdall.rule=Host(`${HOST?Variable HOST not set}`)'
      - 'traefik.http.routers.heimdall.entrypoints=websecure'
      - 'traefik.http.routers.heimdall.service=heimdall'
      - 'traefik.http.routers.heimdall.tls=true'
      - 'traefik.http.services.heimdall.loadbalancer.server.port=80'

networks:
  traefik:
    external: true
