services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    restart: unless-stopped
    #########################################
    ## Uncomment these lines to start proxy with a config.yaml file ##
    # volumes:
    #  - ./config.yaml:/app/config.yaml <<- this is missing in the docker-compose file currently
    # command:
    #  - "--config=/app/config.yaml"
    ##############################################
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}
      - STORE_MODEL_IN_DB=${STORE_MODEL_IN_DB}
    depends_on:
      - db
    # Container doesn't have `curl` installed
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', 'http://localhost:4000/health/liveliness']
    #   interval: 30s
    #   timeout: 10s # Health check command times out after 10 seconds
    #   retries: 3 # Retry up to 3 times if health check fails
    #   start_period: 40s # Wait 40 seconds after container start before beginning health checks

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
