services:
  main:
    ports:
      - ${N8N_PORT}:${N8N_PORT}

  db:
    ports:
      - ${DEV_BIND_IP:-127.0.0.1}:5432:5432

  qdrant:
    ports:
      - ${DEV_BIND_IP:-127.0.0.1}:6333:6333

  redis:
    ports:
      - ${DEV_BIND_IP:-127.0.0.1}:6379:6379

  adminer:
    ports:
      - ${DEV_BIND_IP:-127.0.0.1}:8080:8080

  redisinsight:
    ports:
      - ${DEV_BIND_IP:-127.0.0.1}:5540:5540
