services:
  app:
    image: shlinkio/shlink:4.4.6
    restart: unless-stopped
    environment:
      - ANONYMIZE_REMOTE_ADDR=${ANONYMIZE_REMOTE_ADDR}
      - DB_DRIVER=postgres
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=${POSTGRES_USER}
      - DEFAULT_DOMAIN=${SHLINK_DOMAIN}
      - GEOLITE_LICENSE_KEY=${GEOLITE_LICENSE_KEY}
      - INITIAL_API_KEY=${INITIAL_API_KEY}
      - IS_HTTPS_ENABLED=${IS_HTTPS_ENABLED}

  web:
    image: shlinkio/shlink-web-client
    restart: unless-stopped
    environment:
      - SHLINK_SERVER_URL=${SHLINK_URL}
      - SHLINK_SERVER_API_KEY=${INITIAL_API_KEY}

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 5s
      timeout: 5s
      retries: 5
