version: "3.8"

services:
  hotrod:
    image: jaegertracing/example-hotrod:latest
    restart: unless-stopped
    environment:
      # - JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
