services:
  app:
    image: gitea/gitea:latest
    ports:
      - 222:22
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${DATABASE_DB}
      - GITEA__database__USER=${DATABASE_USER}
      - GITEA__database__PASSWD=${DATABASE_PASS}
      - GITEA__server__PROTOCOL=http
      # - GITEA__server__ROOT_URL=https://${DOMAIN}/
      - GITEA__server__HTTP_PORT=3000
      # - GITEA__server__CERT_FILE=cert.pem
      # - GITEA__server__KEY_FILE=key.pem

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_DB}
