services:
  app:
    networks:
      - default
      - traefik
    environment:
      - GITEA__server__ROOT_URL=https://${GITEA_DOMAIN}/
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      - 'traefik.http.services.gitea.loadbalancer.server.port=3000'
      # HTTPS Host
      - 'traefik.http.routers.gitea.rule=Host(`${GITEA_DOMAIN}`)'
      - 'traefik.http.routers.gitea.entrypoints=websecure'
      - 'traefik.http.routers.gitea.tls=true'
      - 'traefik.http.routers.gitea.tls.certResolver=webcert'
      - 'traefik.http.routers.gitea.service=gitea'

  db:
    networks:
      - default

networks:
  traefik:
    external: true
