services:
  traefik:
    labels:
      # Auth
      - 'traefik.http.routers.traefik-api.middlewares=traefik-forward-auth'

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    container_name: traefik-forward-auth
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=${PROVIDERS_GOOGLE_CLIENT_ID?Variable PROVIDERS_GOOGLE_CLIENT_ID not set}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${PROVIDERS_GOOGLE_CLIENT_SECRET?Variable PROVIDERS_GOOGLE_CLIENT_SECRET not set}
      - SECRET=${SECRET?Variable SECRET not set}
      - WHITELIST=${WHITELIST?Variable WHITELIST not set}
      # INSECURE_COOKIE is required if not using a https entrypoint
      # - INSECURE_COOKIE=true
      - LOG_LEVEL=debug
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181'
      - 'traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User'
      - 'traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181'
