services:
  app:
    image: ghcr.io/yorch/pocketbase-docker:main
    init: true
    environment:
      - PORT=${PORT}
    volumes:
      # `data/pb_data`   -> Files for application data
      # `data/pb_public` -> Files from this directory will be served by the web server
      - ./data:/app/data
