services:
  app:
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      # Service
      - 'traefik.http.services.pocketbase.loadbalancer.server.port=${PORT}'
      # HTTPS Host
      - 'traefik.http.routers.pocketbase.rule=Host(`${POCKETBASE_HOST?Variable POCKETBASE_HOST not set}`)'
      - 'traefik.http.routers.pocketbase.entrypoints=websecure'
      - 'traefik.http.routers.pocketbase.tls=true'
      - 'traefik.http.routers.pocketbase.tls.certResolver=webcert'
      - 'traefik.http.routers.pocketbase.service=pocketbase'

networks:
  traefik:
    external: true
