version: "3.8"

services:
  grafana:
    image: grafana/grafana-oss:9.1.3
    restart: unless-stopped
    # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables
    environment:
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_AUTH_GOOGLE_ENABLED=${GF_AUTH_GOOGLE_ENABLED}
      - GF_AUTH_GOOGLE_CLIENT_ID=${GF_AUTH_GOOGLE_CLIENT_ID}
      - GF_AUTH_GOOGLE_CLIENT_SECRET=${GF_AUTH_GOOGLE_CLIENT_SECRET}
      - GF_AUTH_GOOGLE_ALLOW_SIGN_UP=${GF_AUTH_GOOGLE_ALLOW_SIGN_UP}
    volumes:
      - ./data:/var/lib/grafana
