version: "3.8"

services:
  app:
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Service
      - "traefik.http.services.plausible.loadbalancer.server.port=${PORT}"
      # HTTPS Host
      - "traefik.http.routers.plausible.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.plausible.entrypoints=websecure"
      - "traefik.http.routers.plausible.tls=true"
      - "traefik.http.routers.plausible.tls.certResolver=webcert"
      - "traefik.http.routers.plausible.service=plausible"

networks:
  traefik:
    external: true
