version: '3.8'

services:
  registry:
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      - 'traefik.http.services.registry.loadbalancer.server.port=${REGISTRY_PORT}'
      # HTTPS Host
      - 'traefik.http.routers.registry.rule=Host(`${REGISTRY_DOMAIN}`)'
      - 'traefik.http.routers.registry.entrypoints=websecure'
      - 'traefik.http.routers.registry.tls=true'
      - 'traefik.http.routers.registry.tls.certResolver=webcert'
      - 'traefik.http.routers.registry.service=registry'

  ui:
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      - 'traefik.http.services.registry-ui.loadbalancer.server.port=80'
      # HTTPS Host
      - 'traefik.http.routers.registry-ui.rule=Host(`${REGISTRY_UI_DOMAIN}`)'
      - 'traefik.http.routers.registry-ui.entrypoints=websecure'
      - 'traefik.http.routers.registry-ui.tls=true'
      - 'traefik.http.routers.registry-ui.tls.certResolver=webcert'
      - 'traefik.http.routers.registry-ui.service=registry-ui'

networks:
  traefik:
    external: true
