version: "3.8"

services:
  grafana:
    image: honeygain/honeygain
    restart: unless-stopped
    environment:
      - ACCOUNT_EMAIL=${ACCOUNT_EMAIL}
      - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
      - DEVICE_NAME=${DEVICE_NAME}
    command: "-tou-accept -email ${ACCOUNT_EMAIL} -pass ${ACCOUNT_PASSWORD} -device ${DEVICE_NAME}"
