services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_CLEANUP=true
      # - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_LOG_FORMAT=json
      - WATCHTOWER_POLL_INTERVAL=3600
      # - WATCHTOWER_DEBUG=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      # Monitor and update containers that have a `com.centurylinklabs.watchtower.enable` label set to `true`
      - WATCHTOWER_LABEL_ENABLE=true
      # Update containers that have a `com.centurylinklabs.watchtower.scope` label set with the same value as the given argument. This enables running multiple instances.
      # - WATCHTOWER_SCOPE=myscope
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
      # - "com.centurylinklabs.watchtower.scope=myscope"
