services:
  app:
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      - 'traefik.http.services.odoo.loadbalancer.server.port=8069'
      # HTTPS Host
      - 'traefik.http.routers.odoo.rule=Host(`${DOMAIN:?Variable DOMAIN not set}`)'
      - 'traefik.http.routers.odoo.entrypoints=websecure'
      - 'traefik.http.routers.odoo.tls=true'
      - 'traefik.http.routers.odoo.tls.certResolver=webcert'
      - 'traefik.http.routers.odoo.service=odoo'

  db:
    networks:
      - default

networks:
  traefik:
    external: true
