version: "3.8"

services:
  octobot:
    image: drakkarsoftware/octobot:stable
    restart: unless-stopped
    volumes:
      - ./data/backtesting:/octobot/backtesting
      - ./data/logs:/octobot/logs
      - ./data/tentacles:/octobot/tentacles
      - ./data/user:/octobot/user
