version: "3.8"

services:
  influxdb:
    image: influxdb:2.3-alpine
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${DOCKER_INFLUXDB_INIT_MODE}
      # The username to set for the system's initial super-user (Required).
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      # The password to set for the system's inital super-user (Required).
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      # The name to set for the system's initial organization (Required).
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      # The name to set for the system's initial bucket (Required).
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      # The duration the system's initial bucket should retain data. If not set, the initial bucket will retain data forever.
      - DOCKER_INFLUXDB_INIT_RETENTION=${DOCKER_INFLUXDB_INIT_RETENTION}
      # The authentication token to associate with the system's initial super-user. If not set, a token will be auto-generated by the system.
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    volumes:
      - ./data:/var/lib/influxdb2