services:
  influxdb:
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      # - 'traefik.http.services.influxdb2.loadbalancer.server.port=8086'
      # HTTPS Host
      - 'traefik.http.routers.influxdb2.rule=Host(`${HOST?Variable HOST not set}`)'
      - 'traefik.http.routers.influxdb2.entrypoints=websecure'
      - 'traefik.http.routers.influxdb2.tls=true'
      - 'traefik.http.routers.influxdb2.tls.certResolver=webcert'
      # - 'traefik.http.routers.influxdb2.service=influxdb2'

networks:
  traefik:
    external: true
