version: '3.8'

services:
  ackee:
    image: electerious/ackee
    restart: unless-stopped
    environment:
      - WAIT_HOSTS=mongo:27017
      - ACKEE_MONGODB=mongodb://mongo:27017/ackee
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
