services:
  app:
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      - 'traefik.http.services.linkwarden.loadbalancer.server.port=3000'
      # HTTPS Host
      - 'traefik.http.routers.linkwarden.rule=Host(`${DOMAIN:?Variable DOMAIN not set}`)'
      - 'traefik.http.routers.linkwarden.entrypoints=websecure'
      - 'traefik.http.routers.linkwarden.tls=true'
      - 'traefik.http.routers.linkwarden.tls.certResolver=webcert'
      - 'traefik.http.routers.linkwarden.service=linkwarden'

  db:
    networks:
      - default

  meilisearch:
    networks:
      - default

networks:
  traefik:
    external: true
