services:
  wg-portal:
    image: wgportal/wg-portal:v2
    container_name: wg-portal
    restart: unless-stopped
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    cap_add:
      - NET_ADMIN
    # Use host network mode for WireGuard and the UI. Ensure that access to the UI is properly secured.
    # network_mode: 'host'
    # So we ensure to stay on the same network as the wireguard container.
    network_mode: 'service:wireguard'
    volumes:
      # - /etc/wireguard:/etc/wireguard
      - ./wg/etc:/etc/wireguard
      - ./wg/data:/app/data
      - ./wg/config:/app/config

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - '51820:51820/udp' # WireGuard port, needs to match the port in wg-portal interface config
      - '8888:8888/tcp' # Noticed that the port of the web UI is exposed in the wireguard container.
    volumes:
      - ./wg/etc:/config/wg_confs # We share the configuration (wgx.conf) between wg-portal and wireguard
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
