services:
  app:
    image: ghost:alpine
    restart: unless-stopped
    volumes:
      - ./data/ghost:/var/lib/ghost/content
    environment:
      # See https://ghost.org/docs/config/#configuration-options
      - database__client=mysql
      - database__connection__host=db
      - database__connection__port=3306
      - database__connection__user=${DB_USER}
      - database__connection__password=${DB_PASS}
      - database__connection__database=${DB_DATABASE}
      # - url=http://localhost:8080
      # Contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production
      # (so development mode needs to be explicitly specified if desired)
      # - NODE_ENV=development
      # -----------------------------
      # Mail
      # -----------------------------
      # - mail__transport=SMTP
      # - mail__from="'Some Name' <email@domain.com>"
      # - mail__options__service=${SMTP_SERVICE}
      # - mail__options__host=${SMTP_HOST}
      # - mail__options__port=${SMTP_PORT}
      # - mail__options__secure=${SMTP_SECURE}
      # - mail__options__auth__user=${SMTP_USER}
      # - mail__options__auth__pass=${SMTP_PASS}

  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_DATABASE}
