services:
  app:
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      - 'traefik.http.services.anything-llm.loadbalancer.server.port=3001'
      # HTTPS Host
      - 'traefik.http.routers.anything-llm.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.anything-llm.entrypoints=websecure'
      - 'traefik.http.routers.anything-llm.tls=true'
      - 'traefik.http.routers.anything-llm.tls.certResolver=webcert'
      - 'traefik.http.routers.anything-llm.service=anything-llm'

networks:
  traefik:
    external: true
