version: '3.8'

services:
  app:
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      - 'traefik.http.services.nocodb.loadbalancer.server.port=8080'
      # HTTPS Host
      - 'traefik.http.routers.nocodb.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.nocodb.entrypoints=websecure'
      - 'traefik.http.routers.nocodb.tls=true'
      - 'traefik.http.routers.nocodb.tls.certResolver=webcert'
      - 'traefik.http.routers.nocodb.service=nocodb'

  db:
    networks:
      - default

networks:
  traefik:
    external: true
