services:
  app:
    depends_on:
      db:
        condition: service_healthy
    image: nocodb/nocodb:latest
    restart: unless-stopped
    volumes:
      - ./data/nocodb:/usr/app/data
    environment:
      - NC_DB=pg://db:${POSTGRES_PORT}?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${POSTGRES_DB}

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - NC_SMTP_FROM=${NC_SMTP_FROM}
      - NC_SMTP_HOST=${NC_SMTP_HOST}
      - NC_SMTP_PORT=${NC_SMTP_PORT}
      - NC_SMTP_USERNAME=${NC_SMTP_USERNAME}
      - NC_SMTP_PASSWORD=${NC_SMTP_PASSWORD}
      - NC_SMTP_SECURE=${NC_SMTP_SECURE}
      - NC_SMTP_IGNORE_TLS=${NC_SMTP_IGNORE_TLS}
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
