version: '3.8'

x-environment:
  &default-environment
  - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
  - SECRET_KEY=${SECRET_KEY}
  - PORT=${GLITCHTIP_PORT:-8000}
  - GLITCHTIP_DOMAIN=${GLITCHTIP_URL}
  # Example smtp://email:password@smtp_url:port https://glitchtip.com/documentation/install#configuration
  - EMAIL_URL=consolemail://
  - ENABLE_USER_REGISTRATION
  - ENABLE_ORGANIZATION_CREATION=true

  - DEFAULT_FROM_EMAIL=${EMAIL_FROM}
  # Number of concurrent celery workers. Defaults to number of CPU cores. Highly recommended to change
  - CELERY_WORKER_CONCURRENCY=2
  # Scale between 1 and 3 to prevent excessive memory usage. Change it or remove to set it to the number of cpu cores.
  # - CELERY_WORKER_AUTOSCALE="1,3"
  - CELERY_WORKER_MAX_TASKS_PER_CHILD=100

x-depends_on:
  &default-depends_on
  - postgres
  - redis

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      # Consider removing this and setting a password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped

  web:
    image: glitchtip/glitchtip
    restart: unless-stopped
    depends_on: *default-depends_on
    environment: *default-environment
    volumes:
      - ./data/uploads:/code/uploads

  worker:
    image: glitchtip/glitchtip
    restart: unless-stopped
    depends_on: *default-depends_on
    environment: *default-environment
    volumes:
      - ./data/uploads:/code/uploads
    command: ./bin/run-celery-with-beat.sh

  migrate:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    environment: *default-environment
    command: "./manage.py migrate"
