services:
  app:
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Service
      - 'traefik.http.services.errbit.loadbalancer.server.port=80'
      # HTTPS Host
      - 'traefik.http.routers.errbit.rule=Host(`${DOMAIN:?Variable DOMAIN not set}`)'
      - 'traefik.http.routers.errbit.entrypoints=websecure'
      - 'traefik.http.routers.errbit.tls=true'
      - 'traefik.http.routers.errbit.tls.certResolver=webcert'
      - 'traefik.http.routers.errbit.service=errbit'

networks:
  traefik:
    external: true
